version: '3.8'

services:
  # Database for analytics service
  postgres:
    image: postgres:15-alpine
    container_name: postgres-logs
    environment:
      POSTGRES_DB: loganalytics
      POSTGRES_USER: loguser
      POSTGRES_PASSWORD: logpass123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U loguser -d loganalytics"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: redis-logs
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Log Producer Service
  log-producer-service:
    build:
      context: ./log-producer-service
      dockerfile: Dockerfile
    container_name: log-producer-service
    ports:
      - "8081:8081"
      - "9081:9081"  # Management port
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    depends_on:
      - kafka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  # Log Consumer Service
  log-consumer-service:
    build:
      context: ./log-consumer-service
      dockerfile: Dockerfile
    container_name: log-consumer-service
    ports:
      - "8082:8082"
      - "9082:9082"  # Management port
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - DATABASE_URL=jdbc:postgresql://postgres:5432/loganalytics
      - DATABASE_USERNAME=loguser
      - DATABASE_PASSWORD=logpass123
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  # Log Analytics Service
  log-analytics-service:
    build:
      context: ./log-analytics-service
      dockerfile: Dockerfile
    container_name: log-analytics-service
    ports:
      - "8083:8083"
      - "9083:9083"  # Management port
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_URL=jdbc:postgresql://postgres:5432/loganalytics
      - DATABASE_USERNAME=loguser
      - DATABASE_PASSWORD=logpass123
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
      - "9080:9080"  # Management port
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LOG_PRODUCER_URL=http://log-producer-service:8081
      - LOG_ANALYTICS_URL=http://log-analytics-service:8083
    depends_on:
      - log-producer-service
      - log-analytics-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  virtual-stock-service:
    build:
      context: ./virtual-stock-service
      dockerfile: Dockerfile
    container_name: virtual-stock-service
    ports:
      - "8084:8080"
      - "9084:9080"  # Management port
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    depends_on:
      - kafka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  kbnt-stock-consumer-service:
    build:
      context: ./kbnt-stock-consumer-service
      dockerfile: Dockerfile
    container_name: kbnt-stock-consumer-service
    ports:
      - "8085:8081"
      - "9085:9081"  # Management port
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - DATABASE_URL=jdbc:postgresql://postgres:5432/loganalytics
      - DATABASE_USERNAME=loguser
      - DATABASE_PASSWORD=logpass123
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  # Inherit Kafka from parent docker-compose
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
    volumes:
      - kafka-data:/bitnami/kafka
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper-data:/bitnami/zookeeper
      - zookeeper-logs:/logs

volumes:
  postgres-data:
  kafka-data:
  zookeeper-data:
  zookeeper-logs:

networks:
  default:
    name: kafka-microservices
