version: '3.8'

services:
  # PostgreSQL Database for Virtual Stock Service
  postgres:
    image: postgres:15-alpine
    container_name: kbnt-postgres
    restart: always
    environment:
      POSTGRES_DB: virtualstock
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d virtualstock"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kbnt-network

  # Virtual Stock Service
  virtual-stock-service:
    image: microservices_virtual-stock-service
    container_name: virtual-stock-test
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/virtualstock
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
    ports:
      - "8084:8080"
      - "9084:9080"
    networks:
      - kbnt-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres-data:

networks:
  kbnt-network:
    driver: bridge
