# Perfil Local - Para desenvolvimento no VS Code
spring:
  kafka:
    bootstrap-servers: localhost:9092
    
logging:
  level:
    com.kbnt.logproducer: DEBUG
    root: INFO
    
server:
  port: 8081

management:
  server:
    port: 9081
