spring:
  application:
    name: kbnt-log-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

# Test profile - disable external dependencies
server:
  port: 8081

logging:
  level:
    root: INFO
    com.estudoskbnt: DEBUG
