version: '3.8'

services:
  zookeeper:
    image: registry.redhat.io/amq7/amq-streams-kafka-34-rhel8:2.4.0
    hostname: zookeeper
    container_name: zookeeper
    command: ["/opt/kafka/bin/zookeeper-server-start.sh", "/opt/kafka/config/zookeeper.properties"]
    ports:
      - "2181:2181"
    environment:
      KAFKA_OPTS: "-Djava.security.auth.login.config=/opt/kafka/config/zookeeper_jaas.conf"
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-logs:/var/lib/zookeeper/log
      - ./config/zookeeper.properties:/opt/kafka/config/zookeeper.properties

  kafka:
    image: registry.redhat.io/amq7/amq-streams-kafka-34-rhel8:2.4.0
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    command: ["/opt/kafka/bin/kafka-server-start.sh", "/opt/kafka/config/server.properties"]
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_OPTS: "-Djava.security.auth.login.config=/opt/kafka/config/kafka_server_jaas.conf"
    volumes:
      - kafka-data:/var/lib/kafka/data
      - ./config/server.properties:/opt/kafka/config/server.properties

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.0
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.8.0
    container_name: logstash
    depends_on:
      - kafka
      - elasticsearch
    volumes:
      - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    environment:
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"

volumes:
  zookeeper-data:
  zookeeper-logs:
  kafka-data:
  elasticsearch-data:
