# Configurações do Log Producer Service

server:
  port: 8081
  servlet:
    context-path: /log-producer

spring:
  application:
    name: log-producer-service
  
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      acks: all
      retries: 3
      batch-size: 16384
      linger-ms: 1
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      compression-type: snappy
      enable-idempotence: true
# Configurações dos tópicos
app:
  kafka:
    topics:
      application-logs: application-logs
      error-logs: error-logs
      audit-logs: audit-logs
      financial-logs: financial-logs
  
  processing:
    batch-size: 100
    max-processing-time: 30000
    
  validation:
    max-message-length: 10000
    max-service-name-length: 100
    enable-duplicate-detection: true
    duplicate-cache-ttl: 3600

# Actuator - Monitoramento
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,kafka
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      service: log-producer-service

# Logging
logging:
  level:
    com.kbnt.logproducer: DEBUG
    org.springframework.kafka: INFO
    org.apache.kafka: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{36}] [%X{requestId}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{36}] [%X{requestId}] - %msg%n"

# Info para o Actuator
info:
  app:
    name: Log Producer Service
    description: Microserviço para produção de logs no AMQ Streams usando arquitetura hexagonal
    version: 1.0.0
    profiles: ${spring.profiles.active:default}
