# Enhanced Configuration for Independent Microservices Deployment

server:
  port: 8081
  servlet:
    context-path: /log-producer

spring:
  application:
    name: log-producer-service
  
  # Kafka Configuration with Resilience
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      acks: all
      retries: ${KAFKA_PRODUCER_RETRIES:10}
      batch-size: 16384
      linger-ms: 1
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      compression-type: snappy
      enable-idempotence: true
      # Enhanced error handling
      delivery-timeout-ms: 120000
      request-timeout-ms: 30000
      retry-backoff-ms: 100
      max-in-flight-requests-per-connection: 5
    
    # Health check configuration
    admin:
      fail-fast: false
      connection-timeout: 5000
      request-timeout: 10000

# Topic Configuration with Fallbacks
app:
  kafka:
    topics:
      application-logs: ${TOPIC_APPLICATION_LOGS:application-logs}
      error-logs: ${TOPIC_ERROR_LOGS:error-logs}
      audit-logs: ${TOPIC_AUDIT_LOGS:audit-logs}
      financial-logs: ${TOPIC_FINANCIAL_LOGS:financial-logs}
    
    # Circuit breaker for topic availability
    circuit-breaker:
      enabled: true
      failure-threshold: 5
      timeout: 10000
      reset-timeout: 30000
    
    # Fallback configuration
    fallback:
      enabled: true
      log-to-file: true
      file-path: /tmp/fallback-logs
      max-file-size: 100MB
  
  # Processing configuration
  processing:
    batch-size: ${PROCESSING_BATCH_SIZE:100}
    max-processing-time: ${PROCESSING_MAX_TIME:30000}
    async-processing: true
    thread-pool-size: 10
    
  # Enhanced validation
  validation:
    max-message-length: ${VALIDATION_MAX_MESSAGE:10000}
    max-service-name-length: ${VALIDATION_MAX_SERVICE:100}
    enable-duplicate-detection: ${VALIDATION_DUPLICATE_DETECTION:true}
    duplicate-cache-ttl: ${VALIDATION_CACHE_TTL:3600}
    strict-mode: false
    
  # Service independence configuration
  independence:
    # Start even if some topics are not available
    require-all-topics: false
    # Startup check timeout
    startup-check-timeout: 30000
    # Auto-create topics if they don't exist
    auto-create-topics: true
    # Graceful degradation
    degraded-mode-enabled: true

# Actuator - Enhanced Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,kafka,configprops,env
  endpoint:
    health:
      show-details: always
      show-components: always
      group:
        kafka:
          include: kafka
          show-details: always
        readiness:
          include: readinessState,kafka
  health:
    kafka:
      enabled: true
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${ENVIRONMENT:development}
    export:
      prometheus:
        enabled: true

# Logging Configuration
logging:
  level:
    org.apache.kafka: ${KAFKA_LOG_LEVEL:WARN}
    org.springframework.kafka: ${SPRING_KAFKA_LOG_LEVEL:INFO}
    com.estudoskbnt.logproducer: ${APP_LOG_LEVEL:INFO}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{36}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{36}] - %msg%n"
  file:
    name: logs/log-producer-service.log
    max-size: 100MB
    max-history: 30

# Resilience4j Configuration
resilience4j:
  circuitbreaker:
    instances:
      kafka-topics:
        register-health-indicator: true
        ring-buffer-size-in-closed-state: 100
        ring-buffer-size-in-half-open-state: 10
        wait-duration-in-open-state: 30s
        failure-rate-threshold: 50
        minimum-number-of-calls: 10
  retry:
    instances:
      kafka-send:
        max-attempts: 3
        wait-duration: 1s
        exponential-backoff-multiplier: 2
  timeout:
    instances:
      kafka-send:
        timeout-duration: 10s
