# Kibana Configuration for KBNT System
server.name: kbnt-kibana
server.host: 0.0.0.0
server.port: 5601

# Elasticsearch connection
elasticsearch.hosts: ["http://elasticsearch:9200"]

# Monitoring
monitoring.ui.container.elasticsearch.enabled: true

# Security (disabled for development)
xpack.security.enabled: false

# Logging
logging.appenders:
  file:
    type: file
    fileName: /usr/share/kibana/logs/kibana.log
    layout:
      type: json
      
logging.root:
  level: info

# Index patterns and defaults
kibana.index: ".kibana_kbnt"
kibana.defaultAppId: "dashboard"

# Advanced settings for KBNT
kibana.autocompleteTimeout: 3000
kibana.autocompleteTerminateAfter: 100000

# Data views (formerly index patterns) 
data.search.aggs.shardDelay.enabled: true

# Maps
map.includeElasticMapsService: true

# Dashboard and visualization settings
dashboard.defaultAppId: "dashboard"
telemetry.enabled: false
telemetry.optIn: false

# Time picker settings
timepicker:
  time_defaults:
    from: now-24h
    to: now
  quick_ranges:
    - from: now-15m
      to: now
      display: Last 15 minutes
    - from: now-1h
      to: now
      display: Last 1 hour
    - from: now-24h
      to: now
      display: Last 24 hours
    - from: now-7d
      to: now
      display: Last 7 days
    - from: now-30d
      to: now
      display: Last 30 days
