server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: virtual-stock-service
          uri: http://virtual-stock-service:8080
          predicates:
            - Path=/api/v1/virtual-stock/**
          filters:
            - StripPrefix=0
        - id: log-producer-service
          uri: http://virtual-stock-service:8080
          predicates:
            - Path=/api/v1/logs/**
          filters:
            - StripPrefix=0
        - id: kbnt-log-service
          uri: http://virtual-stock-service:8080
          predicates:
            - Path=/api/v1/kbnt-logs/**
          filters:
            - StripPrefix=0
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    gateway:
      routes:
        - id: virtual-stock-service
          uri: http://virtual-stock-service:8080
          predicates:
            - Path=/api/v1/virtual-stock/**
          filters:
            - StripPrefix=0
        - id: log-producer-service
          uri: http://virtual-stock-service:8080
          predicates:
            - Path=/api/v1/logs/**
          filters:
            - StripPrefix=0
        - id: kbnt-log-service
          uri: http://virtual-stock-service:8080
          predicates:
            - Path=/api/v1/kbnt-logs/**
          filters:
            - StripPrefix=0
