apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: error-logs
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
    topic-type: error
    retention-policy: medium-term
    priority: critical
spec:
  partitions: 3
  replicas: 2
  config:
    # Retention - 7 days
    retention.ms: 604800000
    # Cleanup policy
    cleanup.policy: delete
    # Compression
    compression.type: lz4
    # Segment size - 50MB (smaller for faster access)
    segment.ms: 300000
    # Min in-sync replicas - higher for critical data
    min.insync.replicas: 2
    # Message format version
    message.format.version: 3.4-IV0
    # Maximum message size - 2MB (larger for stack traces)
    max.message.bytes: 2097152
    # Flush settings - more aggressive for errors
    flush.messages: 1000
    flush.ms: 500
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: error-logs-config
  namespace: kafka
data:
  description: "Error and fatal logs requiring immediate attention"
  usage: "ERROR, FATAL level logs with stack traces and context"
  retention: "7 days"
  expected-volume: "low-medium"
  routing-key: "service.level.ERROR,FATAL"
  alert-integration: "true"
