spring:
  redis:
    host: redis-logs
    port: 6379
    database: 0
    
  kafka:
    consumer:
      group-id: log-aggregator-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

# Configuração personalizada para logs
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    com.estudoskbnt: INFO
    
# Custom log aggregation
kbnt:
  log:
    aggregation:
      enabled: true
      redis-key-pattern: "logs:${spring.application.name}:%d{yyyy-MM-dd-HH}"
      batch-size: 100
      flush-interval: 5000
