apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: financial-logs
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
    topic-type: financial
    retention-policy: regulatory
    compliance: pci-dss
spec:
  partitions: 3
  replicas: 2
  config:
    # Retention - 90 days (regulatory requirement)
    retention.ms: 7776000000
    # Cleanup policy - compact for transaction integrity
    cleanup.policy: compact
    # Compression - best compression for financial data
    compression.type: gzip
    # Segment size - 500MB (large for financial efficiency)
    segment.ms: 2419200000
    # Min in-sync replicas - maximum reliability for financial data
    min.insync.replicas: 2
    # Message format version
    message.format.version: 3.4-IV0
    # Maximum message size - 2MB for transaction details
    max.message.bytes: 2097152
    # Flush settings - conservative for financial data
    flush.messages: 100000
    flush.ms: 30000
    # Compact settings
    min.cleanable.dirty.ratio: 0.05
    delete.retention.ms: 172800000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: financial-logs-config
  namespace: kafka
data:
  description: "Financial transaction and payment processing logs"
  usage: "Transaction logs, payment processing, billing events"
  retention: "90 days"
  expected-volume: "high"
  routing-key: "service.financial.payment,transaction,billing"
  regulatory-compliance: "PCI-DSS, SOX"
  encryption-required: "true"
