spring:
  application:
    name: kbnt-log-service
  
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 1
    consumer:
      group-id: kbnt-log-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: com.estudoskbnt.kbntlogservice.model

  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 30s
    socket-timeout: 30s

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.estudoskbnt: INFO
    org.springframework.kafka: DEBUG
    org.elasticsearch: INFO

---
spring:
  config:
    activate:
      on-profile: docker
  
  kafka:
    bootstrap-servers: kafka:29092
    
  elasticsearch:
    uris: http://elasticsearch:9200
